export const arrowDown = "./assets/icon-arrow-down.svg"
export const arrowUp = "./assets/icon-arrow-up.svg"
export const closeIcon = "./assets/icon-close.svg"
export const settingsIcon = "./assets/icon-settings.svg"
export const logo = "./assets/logo.svg"
